name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.head_ref }}

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Terraform init and create workspace
        run: terraform init

      - name: Validate Terraform code
        run: terraform validate

